name: Deploy BlogApi .NET 8

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy source to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "BlogApi/**"
          target: "/var/www/blog-api"
          strip_components: 1

      - name: Build & Run Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/blog-api

            docker stop blog-api || true
            docker rm blog-api || true

            docker build -t blog-api:latest .

            docker run -d \
              --name blog-api \
              --restart unless-stopped \
              -p 8080:8080 \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e ConnectionStrings__DefaultConnection="${{ secrets.DATABASE_URL }}" \
              -e Jwt__Key="${{ secrets.JWT_KEY }}" \
              -e Jwt__Issuer="nhatdev.top" \
              -e Jwt__Audience="nhatdev_users" \
              -e CloudinarySettings__CloudName="${{ secrets.CLOUDINARY_NAME }}" \
              -e CloudinarySettings__ApiKey="${{ secrets.CLOUDINARY_API_KEY }}" \
              -e CloudinarySettings__ApiSecret="${{ secrets.CLOUDINARY_API_SECRET }}" \
              blog-api:latest

            docker ps
            docker logs blog-api --tail 50
