name: Deploy BlogApi .NET 8

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy source to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/demo/be"

      - name: Build and Run Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/demo/be/BlogApi
            
            # Xóa container và image cũ trước khi build
            docker rm -f blog-api-cont || true
            docker rmi blog-api || true
            
            # Build bản mới nhất
            docker build --no-cache -t blog-api .

            # Chạy container với các biến môi trường
            docker run -d \
              --name blog-api-cont \
              -p 3005:8080 \
              --add-host=host.docker.internal:host-gateway \
              --restart always \
              -e ConnectionStrings__DefaultConnection="${{ secrets.DATABASE_URL }}" \
              -e Jwt__Key="${{ secrets.JWT_KEY }}" \
              -e Jwt__Issuer="nhatdev.top" \
              -e Jwt__Audience="nhatdev_users" \
              -e CloudinarySettings__CloudName="${{ secrets.CLOUDINARY_NAME }}" \
              -e CloudinarySettings__ApiKey="${{ secrets.CLOUDINARY_API_KEY }}" \
              -e CloudinarySettings__ApiSecret="${{ secrets.CLOUDINARY_API_SECRET }}" \
              -e ASPNETCORE_ENVIRONMENT=Production \
              blog-api

            # Dọn rác
            docker image prune -f